### ISSUE TITLE
Non-software bottleneck invalidity

### ISSUE THREAD

**Issue by alexhultman** [TechEmpower/FrameworkBenchmarks#4148] opened 2018-10-22 20:48 UTC
If you look at the plaintext chart of round 16 you can pretty much tell immediately from looking at the truncated shape of the chart that you have reached some kind of non-software bottleneck here. The top 8 servers are capped at essentially identical performance, only varying by noise.

That's not good for a benchmark that's about software - if you end up benchmarking things that are not tied to the software then it's essentially an invalid benchmark. Either you need to increase the network capacity or decrease the available CPU-time.

Otherwise you're basically benchmarking noise. It cannot be the case that 8 servers score almost identical at 7 million req/sec.

**Comment by msmith-techempower** [comment] 2018-10-22 20:49
Duplicate of #3538

**Closed by msmith-techempower** 2018-10-22 20:49 UTC
