### ISSUE TITLE
Databases unstable on Travis

### ISSUE THREAD

**Issue by zane-techempower** [TechEmpower/FrameworkBenchmarks#1661] opened 2015-06-09 19:22 UTC
When verifying PR's we are getting a lot of framework fails simply because databases are not available to connect to. Here are some connection results from a recent Travis run. The other frameworks have all the databases up for the most part. On a previous run I had a test failing when only mysql failed to start.

```
--------------------------------------------------------------------------------
  Running Test: wt
--------------------------------------------------------------------------------
database connection test results:
mysql: is GO!
mongodb: is _NO_ GO!: ERROR: [Errno 111] Connection refused
redis: is GO!
postgresql: is _NO_ GO!: ERROR: [Errno 111] Connection refused
cassandra: is _NO_ GO!: ERROR: [Errno 111] Connection refused
elasticsearch: is _NO_ GO!: ERROR: [Errno 111] Connection refused
```

```
--------------------------------------------------------------------------------
  Running Test: wt-postgres
--------------------------------------------------------------------------------
database connection test results:
mysql: is GO!
mongodb: is _NO_ GO!: ERROR: [Errno 111] Connection refused
redis: is GO!
postgresql: is _NO_ GO!: ERROR: [Errno 111] Connection refused
cassandra: is GO!
elasticsearch: is _NO_ GO!: ERROR: [Errno 111] Connection refused
```

Very common for cassandra to fail
```
--------------------------------------------------------------------------------
  Running Test: gemini-mysql
--------------------------------------------------------------------------------
database connection test results:
mysql: is GO!
mongodb: is GO!
redis: is GO!
postgresql: is GO!
cassandra: is _NO_ GO!: ERROR: [Errno 111] Connection refused
elasticsearch: is GO!
```

In job https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/66095360 all databases have started up, however when the tests start, the server reads `null`s from redis. From my experience this means that Redis is down or not available. May suggest instability during test runtime.

Same thing happens in https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/66095480 where is said to be GO but then all the redis tests fail in a way that suggests the database was inoperable.

Two main issues:
* Databases sometimes do not start for the tests
* Redis specifically may be unavailable even when it is reported to be operational when Travis tests it at the start of each run.

**Comment by zane-techempower** [comment] 2015-06-10 22:41
This is related to #1604

**Comment by hamiltont** [comment] 2015-06-12 03:29
For redis, the problem is that it's been misconfigured. It's been added it to the list of supported databases, but someone misunderstood that "supported databases" does not mean "databases framework benchmarks allows" - it instead means "databases that we have configured correctly inside travis ci". Travis cannot use our `database.sh` script - that script overwrites configurations in ways that will break things badly. Instead I configure the databases manually in run-ci [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/run-ci.py#L396), and a quick look at that seems to show that there is nothing being done for redis, so it is inevitably incorrect. The correct fix then is to 1) add a comment to "supported databases" explaining this so it doesn't accidentally happen again 2) modify the default redis setup on travis-ci with our u/p and run something like [this setup script](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/config/create-redis.sh)

In general though, database support on travis ci is killer hard. It's a moving target because they update things (looking at mongo, where 2.4 vs 2.6 is a *huge* distinction and travis has had plans to update for a while - they even pushed out the update then rolled it back recently. It's hard for our scripts to stay solid when the underlying OS environment changes on us).

**Comment by msmith-techempower** [comment] 2015-06-12 14:20
@hamiltont Thanks for the amazing description; I had no idea. For my part, I just wanted those tests that relied on `redis` (and the like) to not be marked as having failed when they 1) weren't even intended to run and 2) didn't start up anyway.

**Comment by hamiltont** [comment] 2015-06-18 03:15
Yea, I understand. What travis-ci means by "failed" is "anything that was not a 100% pass", whereas I think a number of people see "holy crap I broke the build". Sadly there are a number of cases where we (quite sanely, I like to think) would prefer to have a greyed-out "this build didn't make sense for some reason, but that's probably ok"

**Comment by nbrady-techempower** [comment] 2015-12-31 02:18
I think this can be closed, at least for now, seeing as all "current" travis db issues have been resolved. Should open separate issues/pr's as travis updates and changes environments on us.

**Closed by nbrady-techempower** 2015-12-31 02:18 UTC
Labels: Bug: Travis-CI
