### ISSUE TITLE
vagrant up hang undefinitely after "default: SSH auth method: private key"

### ISSUE THREAD

**Issue by matt-42** [TechEmpower/FrameworkBenchmarks#5870] opened 2020-07-14 12:45 UTC
Hi,

I'm not able to start vagrant anymore. Did anybody solved this already ? I'm on archlinux.
Here is the log:

```
$ vagrant up                                                                                                                                             15:02:31
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20200701.0.0' is up to date...
==> default: A newer version of the box 'ubuntu/bionic64' for provider 'virtualbox' is
==> default: available! You currently have version '20200701.0.0'. The latest is version
==> default: '20200702.0.0'. Run `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 2001 (guest) => 22001 (host) (adapter 1)
    default: 3000 (guest) => 23000 (host) (adapter 1)
    default: 8000 (guest) => 28000 (host) (adapter 1)
    default: 8080 (guest) => 28080 (host) (adapter 1)
    default: 8081 (guest) => 28081 (host) (adapter 1)
    default: 8082 (guest) => 28082 (host) (adapter 1)
    default: 8085 (guest) => 28085 (host) (adapter 1)
    default: 9000 (guest) => 29000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
   [hang undefinitely here]
```

**Comment by nbrady-techempower** [comment] 2020-07-14 14:50
Hmm, try changing the vm box back to xenial64. This was a recent change.

in `deployment/vagrant/core.rb`

change:
`    override.vm.box = "ubuntu/bionic64"`
to:
`    override.vm.box = "ubuntu/xenial64"`

and see if that helps. Might be a couple of days before I can look into this.

**Comment by matt-42** [comment] 2020-07-14 17:56
Same problem with xenial, I also tried `vagrant box update`

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/xenial64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/xenial64' version '20200708.0.0' is up to date...
==> default: Setting the name of the VM: vagrant_default_1594747387740_36414
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 2001 (guest) => 22001 (host) (adapter 1)
    default: 3000 (guest) => 23000 (host) (adapter 1)
    default: 8000 (guest) => 28000 (host) (adapter 1)
    default: 8080 (guest) => 28080 (host) (adapter 1)
    default: 8081 (guest) => 28081 (host) (adapter 1)
    default: 8082 (guest) => 28082 (host) (adapter 1)
    default: 8085 (guest) => 28085 (host) (adapter 1)
    default: 9000 (guest) => 29000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by nbrady-techempower** [comment] 2020-07-14 19:24
@joanhey Are you currently using vagrant? The vagrant/vbox setup no longer works for me locally as I'm using Hyper-V, but curious if you've brought up a new box recently.

@matt-42 The toolset works on wsl2 now if you're in windows (so long as you install docker-ce in wsl2 and disable docker for windows) or on ubuntu/linux without much setup. This may be an easier route for you in the meantime?

**Comment by matt-42** [comment] 2020-07-15 09:50
I'm on archlinux so I'll try to run the toolset without vagrant. Thanks for your help

**Comment by nbrady-techempower** [comment] 2020-07-15 15:21
@matt-42 Thanks! Let me know how it goes. We'll leave this open until we can confirm it works.

**Comment by joanhey** [comment] 2020-07-15 17:39
@matt-42  when you update `virtualbox` (6.0 to 6.1) or the `override.vm.box` to another distro version (xenial to bionic in the last tfb-update), it's better to destroy the vm box first.

```
vagrant destroy
vagrant up
```

It's working here without problems with debian, vagrant 2.2.9 and vbox v6.0.
Now I'll try with vbox v6.1.

**Comment by nbrady-techempower** [comment] 2020-07-16 02:08
Thanks for the confirmation @joanhey! I'm going to close this @matt-42 but ping me if you end up trying again and still have trouble.

**Closed by nbrady-techempower** 2020-07-16 02:08 UTC

**Comment by joanhey** [comment] 2020-07-27 11:36
Update:
I have the same error than @matt-42 when I use vbox v6.1.

Reverted to vbox v6.0.24, and all it's working correctly.

**Comment by matt-42** [comment] 2020-07-27 17:33
I did not mention it but I also have virtualbox 6.1.

**Comment by matt-42** [comment] 2020-08-05 15:37
Setting the number of vb.cpus = 1 in core.rb seems to be a workaround.

**Comment by joanhey** [comment] 2021-02-06 23:44
I have needed to upgrade to 6.1 for other reasons, and the problem still exists.

Removing PR #3826,  fix it in linux.

And I think also fail in Windows and Mac. I don't have any Win or Mac at hand to test it.

Info:
https://github.com/hashicorp/vagrant/issues/10578#issuecomment-459081990
https://bugs.launchpad.net/cloud-images/+bug/1829625

https://www.virtualbox.org/ticket/18319?cversion=0&cnum_hist=24

I commented the lines from that PR, to use it locally.

Waiting for the new toolset, which I think doesn't use vagrant, to test it.

**Comment by slhmy** [comment] 2021-04-20 03:16
6.1 failed in Mac confirmed. But it works fine after I switch to 6.0.24.
