### ISSUE TITLE
[Question] License for database

### ISSUE THREAD

**Issue by redknightlois** [TechEmpower/FrameworkBenchmarks#3792] opened 2018-05-28 18:58 UTC
Hi,

I am writing the RavenDB (https://ravendb.net) driver for TechEmpower running under the #aspdotnet framework. The default installation without a license is restricted to 3 cores + 6 Gb of memory, to unlock the complete use of resources we would need to embed a license key in the process. How do you handle that?

We can give you a license that could be injected into your test cluster as an environment variable. If that doesn't work I would need advice on how we can help you to include RavenDB on TechEmpower. 

Kind regards,

**Comment by bhauer** [comment] 2018-05-28 23:56
Hi @redknightlois.  Thanks for your interest in the project and for offering to help with creating test implementations with a new database platform!

To-date, we have not included any commercial/licensed software in this project, so we do not have an existing model to apply here.  Some quick thoughts:

1. We could likely use the approach you describe—add the license as an environment variable within the test environments.  We may also want to create a sanity check to alert us if, for any reason, RavenDB is running without a license key (and is therefore running with only 3 cores), since that would yield invalid results for any tests that use it as the database platform.

2. Would the license work in both the physical hardware and cloud environments concurrently?  (That is, is the license limited to a single deployment?)  Would each environment need a unique license?

3. I assume others or you could provide additional test implementations that use RavenDB on other web platforms, correct?

4. A goal of this project is reproducibility and the ability for anybody to verify our results.  Licensed software presents a challenge for reproducibility, and I'd like to consider options and other opinions on that.

Thanks again!

**Comment by ayende** [comment] 2018-05-29 06:28
We don't need enterprise license here, mind. The developer license would be just as good, in fact, it is desirable in this regard for several reasons.
First, it is available (for free) for anyone.  The only limit it has it that it cannot be used for production deployments.

In other words, even though we'll require a license, we can make this license available.
The only caveat here is that we'll disable that particular license key from being used for domain generation / DNS updates on our end (since it is public).

**Comment by bhauer** [comment] 2018-05-31 16:19
We're trying to wrap Round 16 this week.  In fact, as I write this, the [current Citrine run](https://tfb-status.techempower.com/results/dc845fa8-4687-4c2d-9a7a-9bd6c5ec796b) is just minutes from completing.  When that finishes, we are planning on kicking off an Azure run to run concurrently with the next Citrine run and—assuming the results look good—these will likely become Round 16 final.  I mention all of this to set expectations: unless these runs have serious problems, there will be no new additions in Round 16.

That said, with [continuous benchmarking](https://tfb-status.techempower.com/), results are available for review days after submission.  Plus, with the increased stability provided by the recent Docker conversion, we can "promote" continuous runs to official Rounds more easily.

It sounds as if a Developer license is ideal for including RavenDB in this project.  If I understand @ayende correctly, that also addresses my concern (number 4) about reproducibility.  Am I correct that a developer license would be "valid" when participants in this project run benchmarks independently since these exercises are not considered production deployments for the purposes of the license?

**Comment by redknightlois** [comment] 2018-05-31 16:35
We will be registering the license as development and revoke its ability to run secured environments and clustering (which is good enough for benchmarking purposes). I am actually in the process of doing so and issue a [DO NOT MERGE] PR to get input from you.

**Comment by ayende** [comment] 2018-05-31 19:02
@bhauer Yes, the license will be valid for reproducing this. 
Note that the reason we need to revoke the secured option is that the license will be public, and that is can be used to generate a DNS name for hosting the db. We want to avoid the license "leak" allowing multiple people access to the same domain, since they might end up assuming that this is a secured setup.

Developer licenses are also available (freely) from our website, so anyone who want can just use that license as well, with no limitation.

**Comment by nbrady-techempower** [comment] 2020-01-06 19:30
@redknightlois @ayende Just perused https://ravendb.net/ and I'd be super interested in seeing it in the benchmarks. I've recently updated the toolset to make it a bit less painful to add a new database. If it's still a possibility, I can help get this up and running. Going to close this for now, but let me know.

**Closed by nbrady-techempower** 2020-01-06 19:30 UTC

**Comment by ayende** [comment] 2020-01-12 14:06
Hi, we are still very interested in doing this, yes. 
What would be the next step, then?

**Comment by nbrady-techempower** [comment] 2020-01-13 19:25
Since the last update, adding this to the toolset would be as simple as adding a `ravendb` folder in https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/toolset/databases 

This allows people to add `"database": "ravendb"` to their config files to target your db. In that folder, you'd need to implement a few methods in python that I can help with if needed. If you want to start work on it, you can open a PR and I'll add a WIP tag to it and we can collab there.

Overall, it shouldn't be much work at all to get this going. Here's some more information: https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-Adding-a-Database

**Comment by ayende** [comment] 2020-01-21 07:42
Thanks for the info. We'll start looking into this and ping here if we need any help.
https://issues.hibernatingrhinos.com/issue/RavenDB-11198
