### ISSUE TITLE
All frameworks based on Node.js must be tested on the same docker image.

### ISSUE THREAD

**Issue by KostyaTretyak** [TechEmpower/FrameworkBenchmarks#8427] opened 2023-09-17 14:42 UTC
I created a [PR to add the Ditsmod](https://github.com/TechEmpower/FrameworkBenchmarks/pull/8422) and it shows one of the best results on the Node.js platform, it's even better than Fastify in most cases... BUT the problem is that the tests for Ditsmod use the `node:18.17.1-slim` docker image and Fastify is used by `node:18.12.1-alpine` and this has a noticeable effect on the tests.

The tests themselves have no special requirements for Node.js, so I'm sure they will work on new version of Node.js. That is, they can all be updated at once, for example to `node:18.17.1-slim`, it is not even necessary for maintainers to do it.

So the tests will have more correct results.

**Comment by joanhey** [comment] 2023-09-17 15:34
Sorry, but Distmod still never run with the Citrine Servers. The PR is still not merged.
If you made your test in local, possibly will be very different numbers that with the Citrine Servers.

And you are welcome to change any framework benchmark, to have better results.

**Comment by KostyaTretyak** [comment] 2023-09-17 15:41
@joanhey, it is not entirely clear what you wanted to say in this comment. Granted, my local tests won't be the same as on Citrine Servers, but what does that change? Do you think the tests will change disproportionately?

As for the fact that I can change any test to improve it... The change I proposed is probably not to everyone's liking, so changing the rules should be done by the owner of these tests in the first place.

**Comment by joanhey** [comment] 2023-09-17 15:45
I can assure you that the results can change a lot in local vs Citrine servers.

**Comment by KostyaTretyak** [comment] 2023-09-17 15:48
Absolutely agree. Just what does it change in the context of my issue? Do you doubt that frameworks using different versions of docker images will show different results?

**Comment by joanhey** [comment] 2023-09-17 15:53
No, but i'll be not a big change.
And if it's exist a big difference, perhaps is better create an issue in the creators of the docker image.

I know form PHP, that using the official PHP docker images,  a lot of times is a lot slower than use a normal Ubuntu image and download the required packages.
But a benchmark is for that, to show discrepancies. The problem is not in the benchmark it's in the docker file.
And the correct think is create an issue to the docker file, not in the benchmark.

**Comment by KostyaTretyak** [comment] 2023-09-17 16:05
Tests should have as much as possible the same initial conditions for all frameworks. As you can guess, it is not a big problem for me that my framework shows better results based on Node.js. But I want fair competition. My proposed changes add precision to the results of these competition.

**Comment by joanhey** [comment] 2023-09-17 16:14
I am creating benchmarks since 2008, and since that time I have seen almost everything.
Some testing with very different size responses for the same body, other testing and say that is faster, but in reality they are testing a 502 from the sever, not from the framework, etc etc

I'm the first that want a fair benchmark, and that all use the best tools for that, without make tricks.

But I say you that if one docker image is slower, the best thing is to create an issue to the creators of the dockerfile, not in the benchmark.
The people that see the benchmarks don't know which docker image is using. 

Use the benchmark as a tool to see problems in your framework or toolset. And inform about problems to create a faster and healthy ecosystem to your framework or language.

Please don't use the benchmark only like a competition of results numbers.
Thanks.

**Closed** 2023-09-18 15:11 UTC
