### ISSUE TITLE
sudo -s ulimit does not work

### ISSUE THREAD

**Issue by MalcolmEvershed** [TechEmpower/FrameworkBenchmarks#309] opened 2013-05-24 04:01 UTC
In benchmarker.py, in __setup_server, [this call](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/benchmarker.py#L248) to sudo -s ulimit -n 8192 does not work because sudo spawns a new shell which then calls the ulimit shell built-in which only affects that shell, which then exits. I'm not quite sure how to fix this, but wanted to make sure that you guys were aware of this (in case you see mysterious file errors).

In __setup_client, there is a call to sudo -s ulimit which doesn't do anything, but that is unnecessary if you merge [this pull request](https://github.com/TechEmpower/FrameworkBenchmarks/pull/308) which fixes the issue for the client because the next ssh to the client will cause the /etc/security/limits.conf setting to be used.

**Comment by LadyMozzarella** [comment] 2015-03-23 19:17
Closing this issue due to inactivity. If this should remain as an issue, please reopen.

**Comment by hamiltont** [comment] 2015-03-29 17:07
I think we should keep this one open for now - [here's the updated offending line](https://github.com/TechEmpower/FrameworkBenchmarks/blob/9eee16199f5f618a4053c1c77a85802d9610d884/toolset/benchmark/benchmarker.py#L380) - we need to re-SSH into the machines and re-run `sudo sysctl -a` to confirm that the settings we made to the kernel have persisted. I'll try to debug at some point, so I'll assign to myself for now

**Comment by hamiltont** [comment] 2015-03-29 17:07
If the kernel parameter changes are not sticking, that could explain a number of other issues

**Comment by msmith-techempower** [comment] 2016-01-29 18:11
Ugh, sounds bad; kicking it down the road.

**Comment by msmith-techempower** [comment] 2017-01-11 22:30
Does not appear to be an issue; confirmed with #2492

**Closed by msmith-techempower** 2017-01-11 22:30 UTC
Labels: Bug: Toolset
