### ISSUE TITLE
Unable to visualize benchmark results

### ISSUE THREAD

**Issue by rkraman** [TechEmpower/FrameworkBenchmarks#2412] opened 2016-12-16 20:16 UTC
Hello,

In TechEmpower Google forum got the information that to view the benchmark results that is run locally I had to paste the results.json file in the following website:
**https://www.techempower.com/benchmarks/#section=test**

I ran the following test 
**toolset/run-tests.py --install server --test nodejs-postgres --type query**

Got the results.json and pasted it in the above URL.

I am using Chrome V 55.0.2883.87m (64-bit) and it says it is up to date.  So this is the latest version.

When I opened the console (Ctrl +Shft + J) and paste the results.json and submit, I get the following error message:

_tfb.js?m=44:15 Uncaught TypeError: Cannot read property 'desc' of undefined
    at R (tfb.js?m=44:15)
    at tfb.js?m=44:27
    at N (tfb.js?m=44:5)
    at Ra (tfb.js?m=44:24)
    at tfb.js?m=44:27
    at tfb.js?m=44:4
R @ tfb.js?m=44:15
(anonymous) @ tfb.js?m=44:27
N @ tfb.js?m=44:5
Ra @ tfb.js?m=44:24
(anonymous) @ tfb.js?m=44:27
(anonymous) @ tfb.js?m=44:4_

Later I installed FF V 50.1.0 latest, I get a different error message.

_TypeError: La[z[w.hardware.name.toLowerCase(...)]] is undefined[Learn More]  tfb.js:15:307
	R https://www.techempower.com/benchmarks/js/tfb.js:15:307
	Ra/< https://www.techempower.com/benchmarks/js/tfb.js:27:9
	N https://www.techempower.com/benchmarks/js/tfb.js:5:33
	Ra https://www.techempower.com/benchmarks/js/tfb.js:24:44
	Ca/</< https://www.techempower.com/benchmarks/js/tfb.js:27:90
	Ga/< https://www.techempower.com/benchmarks/js/tfb.js:4:84_

I tried different benchmark, instead of query ran the entire nodejs-postgres test and in Chrome I got the exact same error as above and in FF got the following:

_TypeError: La[z[w.hardware.name.toLowerCase(...)]] is undefined[Learn More]  tfb.js:15:307
	R https://www.techempower.com/benchmarks/js/tfb.js:15:307
	Ra/< https://www.techempower.com/benchmarks/js/tfb.js:27:9
	N https://www.techempower.com/benchmarks/js/tfb.js:5:33
	Ra https://www.techempower.com/benchmarks/js/tfb.js:24:44
	Ca/</< https://www.techempower.com/benchmarks/js/tfb.js:27:90
	S https://www.techempower.com/benchmarks/js/tfb.js:15:465
	Ca/< https://www.techempower.com/benchmarks/js/tfb.js:27:75
	.each https://www.techempower.com/benchmarks/js/jquery-1.9.0.min.js:1:15877
	st.prototype.each https://www.techempower.com/benchmarks/js/jquery-1.9.0.min.js:1:12593
	Ca https://www.techempower.com/benchmarks/js/tfb.js:27:53
	ha https://www.techempower.com/benchmarks/js/tfb.js:4:1
	oa https://www.techempower.com/benchmarks/js/tfb.js:27:134
	Wa/B.test/< https://www.techempower.com/benchmarks/js/tfb.js:32:335
	st.event.dispatch https://www.techempower.com/benchmarks/js/jquery-1.9.0.min.js:2:5365
	st.event.add/y.handle https://www.techempower.com/benchmarks/js/jquery-1.9.0.min.js:2:2108_

Will appreciate if anyone can help sort out this issue.
Attaching the results.json file (renamed it as .txt file so that I can attach)
[results.json.txt](https://github.com/TechEmpower/FrameworkBenchmarks/files/658139/results.json.txt)

Thanks in advance and happy holidays.

-RR

**Comment by knewmanTE** [comment] 2016-12-16 21:39
Hmm, I am also able to reproduce the issue. I will investigate. Thanks for bringing this to our attention!

**Comment by rkraman** [comment] 2016-12-18 00:23
@knewmanTE.  Thanks for looking into this.
Do we an alternate method to view the result or is this the only one.
If this is the only one can I get an approximate date for the fix.

-RR

**Comment by knewmanTE** [comment] 2016-12-19 17:40
@rkraman, our developer who handles the website will be out of the office for a couple weeks for Christmas, so it might take a bit of time for the issue to get resolved.

If you are okay with just viewing numbers and not necessarily getting the visualization, you can view the results of any run. If you look in `results/<TIMESTAMP>/logs/nodejs-postgres/<TEST>/raw`, you should be able to see the requests/second for each of the wrk executions. Our results site just displays the best performance out of all of the wrk executions. This is also a useful way of seeing under what circumstances a given framework performs best and worst.

**Comment by bhauer** [comment] 2017-01-09 18:07
@rkraman Sorry about that.  It should be fixed up now.

The issue was caused by a recent change to the rendering site that replaced the individual tabs for environment types (i7, AWS, etc.) with tabs for environment flavors (physical, cloud).  The "test" feature wasn't set up to impersonate an environment flavor at all.

**Closed by bhauer** 2017-01-09 18:07 UTC
Labels: Bug: Results Web Site
